resolver: lts-13.25
packages:
 - .
 - /home/andrew/src/afcowie/chronologique
 - /home/andrew/src/afcowie/http-streams
 - /home/andrew/src/afcowie/locators
 - /home/andrew/src/afcowie/rosterium
 - /home/andrew/vcs/haskell/unbeliever
 - /home/andrew/src/oprdyn/publish
 - /home/andrew/src/oprdyn/briefcase

extra-deps:
 - megaparsec-7.0.5

allow-newer: true

#- ../kalman
#- ../konvig
#- ../performers
#- ../shlurp
#- ../tablinator
#- ../maturity
