resolver: lts-13.12
packages:
 - ../chronologique
 - ../http-streams
#- ../kalman
#- ../konvig
 - ../locators
#- ../performers
 - ../rosterium
#- ../shlurp
#- ../tablinator
#- ../maturity
 - /home/andrew/src/oprdyn/unbeliever
 - /home/andrew/src/oprdyn/publish

allow-newer: true
